name: Build and Deploy Website

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-blog:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blog
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './blog/package-lock.json'
    - name: Install Dependencies 
      run: npm install
    - name: Build Blog
      run: npm run build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blog
        path: ./build

  build-links:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./links
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: links
          path: .         

  deploy-to-github-pages:
    needs: build-blog
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
      - name: Move links to root dir
        shell: bash
        run: |
          cp -r ./links/* .
          ls -al
